spring:
  application:
    name: springboot-mybatis-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_db?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cz.springbootMybatisDemo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 250
